### ISSUE TITLE
Есть вопросы

### ISSUE THREAD

**Issue by alexander-litvinovich** [Enhant/send-task#3]
Привет!
Мы очень рады новым выполненным тестовым заданиям и заинтересованности соискателей.

Прежде чем мы будем что-либо ревьювить, нас интересует:
Есть ли посмотреть задеплоеная версия тестового задания?
![image](https://user-images.githubusercontent.com/11630525/62212395-4d587b00-b3a9-11e9-9f0e-f7eeb5a59023.png)

Почему такая странная история коммитов?
![image](https://user-images.githubusercontent.com/11630525/62212719-0a4ad780-b3aa-11e9-8d80-0014faa3e92f.png)

Гражданин @Horchelas тоже подключится к обсуждению?

**Comment by Horchelas** [comment]
Horchelas - это я и есть. Я не совсем понимаю, когда мой компьютер добавляет репозиторий от имени Horchelas, а когда от Enhant. 
4 мая я даже не знал об этом задании - я начал его 26 июля
Версия сайта на heroku -  https://send-task.herokuapp.com/  

>Среда, 31 июля 2019, 14:48 +02:00 от Alexander Litvinovich <notifications@github.com>:
>
>Привет!
>Мы очень рады новым выполненным тестовым заданиям и заинтересованности соискателей.
>Прежде чем мы будем что-либо ревьювить, нас интересует:
>Есть ли посмотреть задеплоеная версия тестового задания?
>Почему такая странная история коммитов?
>Гражданин  @Horchelas тоже подключится к обсуждению?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Даниил Кузин
daniel_prod@mail.ru

**Comment by sergeycw** [comment]
Зачем такое облако тегов, что за жуть

**Comment by Enhant** [comment]
Не я их ставил

**Comment by Enhant** [comment]
Ну так что насчёт проблемы с формой? Где я ошибся в API?

**Comment by alexander-litvinovich** [comment]
Форма умеет отправлять письма, но не умеет показывать актуальное состояние треков
![image](https://user-images.githubusercontent.com/11630525/62420856-f7821c80-b6a1-11e9-924d-19d9fa191f11.png)

Возможно поможет более внимательное чтение задания, можно еще глянуть `track.get` в [описании API](https://sendsay.ru/api/api.html#%D0%A1%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5-%D0%B0%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0) и как реализован журнал заданий в интерфейсе (иконка с колокольчиком в шапке)

**Comment by Enhant** [comment]
Итак, форма отправляет данные и отслеживает состояние треков, однако, лично у меня никакой вызов не сопровождается ничем кроме ошибки по статусу -2 с "error: "emailsender"", т.е. я как то неправильно отправляю форму?

**Comment by alexander-litvinovich** [comment]
Следует использовать подтвержденного email-отправителя (утром был  danielkuzinsn@gmail.com), тогда ошибки emailsender не будет

**Comment by Enhant** [comment]
Мне следовало догадаться - дело в том, что моя почта - daniel.kuzin.sn@gmail.com(с точками). 
Вот исправленная версия - https://send-task2.herokuapp.com/ 
Теперь проблема с base64 - всегда посылается закодированный файл, размером лишь 10 байт. При этом сама кодирующая функция возвращает нормальный, рабочий результат.

**Comment by alexander-litvinovich** [comment]
![Hell no](https://media.giphy.com/media/aUACY1m2UUrgQ/giphy.gif)

**Лучше будет сделать так:** Когда уверенность в выполненности тестового задания превысит 75-85%, то следует открыть ПР со всеми файлами, приложить ссылку на задеплоенную версию в описании ПР и позвать туда следующих персонажей как ревьюверов:
— bitoptik
— nipanasovich
— rosendi
— alexander-litvinovich

А после этого мы будем посмотреть: работоспособность функционала, наличие и размеры чувства прекрасного, организацию кода и вот это вот всё. И напишем свои комментарии, конечно же.
